import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { cookies } from "next/headers";
import { CookiesKey } from "@/lib/constants";
import SplashCursor from "@/components/react-bits/SplashCursor";
import { getLocales } from "@/lib/locales";
import { LocaleType } from "@/types";
import Header from "@/components/header";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LocaleType }>;
}>) {
  const { lang } = await params;
  const locales = await getLocales(lang);

  const cookieStore = await cookies();
  const savedTheme = cookieStore.get(CookiesKey.THEME)?.value || null;

  return (
    <html lang={lang}>
      <body
        className={` ${
          spaceGrotesk.variable
        } antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={savedTheme ? savedTheme : "system"}
          // defaultTheme={savedTheme || "system"}
          enableSystem
          disableTransitionOnChange
          storageKey={CookiesKey.THEME}
        >
          {/* <SplashCursor /> */}
          <Header lang={lang} menu={locales.header.navigation} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
